In [1]:
from results_analysis import *
import numpy as np
mylist = ["dataset", "activation","encoding","nmax", "ntype","mean_hit","dev_hit","mean_ndcg","dev_ndcg"]
mylist_all = ["activation","encoding","nmax","mean_hit","dev_hit","mean_ndcg","dev_ndcg"]
pd.set_option('display.max_rows', None)

In [2]:
devhit = lambda df: round(df[df['encoding'].isin([r'\None', r'\RotatoryCon', r'\RMHA'])]["dev_hit"].mean(), 4)
devndcg = lambda df: round(df[df['encoding'].isin([r'\None', r'\RotatoryCon', r'\RMHA'])]["dev_ndcg"].mean(), 4)
whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
showhead = lambda df, num, head: print(best(df[mylist], num).head(head).to_latex(index=False))

## List all the trainings of a folder

In [3]:
# dfgames = print_it("games", start=0)
# dfmen = print_it("men", start=0)
# dfbeauty = print_it("beauty", start=0)
# dffashion = print_it("fashion", start=0)
#####################
# dfsubmen = print_it("submen", start=0)
# dfsubfashion = print_it("subfashion", start=0)
# dfsubgames = print_it("subgames", start=0)
# dfsubmen2 = print_it("submen2", start=0)
######################
dfnewdeal = print_it("newdeal", start=0)

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True

In [4]:
# dfgames = renamer(dfgames)
# dfbeauty = renamer(dfbeauty)
# dffashion = renamer(dffashion)
# dfmen = renamer(dfmen)
# ######################
# dfsubmen = renamer(dfsubmen)
# dfsubfashion = renamer(dfsubfashion)
# dfsubgames = renamer(dfsubgames)
# dfsubmen2 = renamer(dfsubmen2)
######################
dfnewdeal = renamer(dfnewdeal)

## Filtering

In [5]:
import numpy as np
apply_min = True # min number of 2 runs
No_nan = False # If true ignore nan cases
encoding = True # If encoding onl metrics L2
pseudo = False # If pseudo only different of L2
add_confidence = True
nosas = True
###########################################################################
# max_apply = [] # [1.e-04, 1.e-02, 1.e-01, 1.e+00] #  [0.0001, 0.1] #, np.nan]
# dfmen = filter_dataframe(dfmen, apply_min, No_nan, encoding, pseudo, nosas,
#                          'men', add_confidence, max_apply=max_apply, ntype_apply=[])
# dfgames = filter_dataframe(dfgames, apply_min, No_nan, encoding, pseudo, nosas,
#                            'games', add_confidence, ntype_apply=[])
# dfbeauty = filter_dataframe(dfbeauty, apply_min, No_nan, encoding, pseudo, nosas,
#                             'beauty', add_confidence, ntype_apply=[])
# dffashion = filter_dataframe(dffashion, apply_min, No_nan, encoding, pseudo, nosas,
#                              'fashion', add_confidence, ntype_apply=[])
###########################################################################
# max_apply = [0.0001, 0.1]
# dfsubmen = filter_dataframe(dfsubmen, apply_min, No_nan, encoding, pseudo, nosas, 'submen', 
#                             add_confidence, max_apply=max_apply)
# dfsubfashion = filter_dataframe(dfsubfashion, apply_min, No_nan, encoding, pseudo, nosas, 'subfashion', 
#                                 add_confidence, max_apply=max_apply)
# dfsubgames = filter_dataframe(dfsubgames, apply_min, No_nan, encoding, pseudo, nosas, 'subgames', 
#                               add_confidence, max_apply=max_apply+[np.nan])
# dfsubmen2 = filter_dataframe(dfsubmen2, apply_min, No_nan, encoding, pseudo, nosas, 'submen2', 
#                               add_confidence, max_apply=max_apply)
###########################################################################
max_apply = [0.0001, 0.1]
dfnewdeal = filter_dataframe(dfnewdeal, apply_min, No_nan, encoding, pseudo, nosas, 'submen', 
                             add_confidence, max_apply=max_apply)

In [6]:
# dfnewdeal[dfnewdeal["dev_hit"] < 3]

In [13]:
showhead(dfnewdeal, 12, 4)

\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation &   encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
 Submen &       silu & \textbackslash LearntCon & 0.0001 &    2.0 &     58.08 &    11.49 &      26.41 &      6.37 \\
 Submen &       silu &      \textbackslash RMHA & 0.1000 &    2.0 &     44.12 &     2.58 &      19.73 &      1.17 \\
 Submen &      leaky &      \textbackslash RMHA & 0.0001 &    2.0 &     42.86 &     5.52 &      20.57 &      5.34 \\
 Submen &       silu &      \textbackslash RMHA & 0.0001 &    2.0 &     42.45 &     2.91 &      18.91 &      1.11 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_61520\56667012.py:5: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  showhead = lambda df, num, head: print(best(df[mylist], num).head(head).to_latex(index=False))

In [10]:
showhead(dfnewdeal, 3, 4)

\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation &     encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
 Submen &       silu &        \textbackslash RMHA & 0.1000 &    2.0 &     44.12 &     2.58 &      19.73 &      1.17 \\
 Submen &       silu &        \textbackslash RMHA & 0.0001 &    2.0 &     42.45 &     2.91 &      18.91 &      1.11 \\
 Submen &      leaky & \textbackslash RMHAROPEONE & 0.0001 &    2.0 &     40.69 &     0.75 &      18.90 &      0.60 \\
 Submen &      leaky & \textbackslash RMHAROPEONE & 0.1000 &    2.0 &     40.66 &     0.74 &      18.67 &      0.39 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_61520\56667012.py:5: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  showhead = lambda df, num, head: print(best(df[mylist], num).head(head).to_latex(index=False))

In [6]:
stats = {"Subgames": {
    "name": "Subgames",
    "users": 5000,
    "items": 4601,
    "interactions": 33353,
    "density": r"$1.3341 times 10 3$",
},
"Submen2": { # old submen3
    "name": "Submen2",
    "users": 10000,
    "items": 45129,
    "interactions": 74391,
    "density": r"1.648 times 10 4$",
},
"Submen": {
    "name": "Submen",
    "users": 8332,
    "items": 10000,
    "interactions": 28603,
    "density": r"$2.860 times 10 4$",
},
"Subfashion": {
    "name": "Subfashion",
    "users": 3840,
    "items": 5000,
    "interactions": 16080,
    "density": r"$3.564 times 10 4$",
}}

def density_table(list_df, stats):
    data = pd.DataFrame(columns=["Dataset", "Users", "Items", "Interactions", "Hit Dev.",
                             "NDCG Dev.", "CI-length", "Sparsity"])
    for (name, df1) in list_df:
        # Drop rows with NaN values and filter by 'encoding' == 'carca'
        if "games" not in name:
            df1 = df1.dropna(axis=0)
        df1 = df1[df1['encoding'].isin([r'\None'])]

        # Append the results to the DataFrame
        data = data.append({
            "Dataset": name,
            "Users": stats[name]["users"],
            "Items": stats[name]["items"],
            "Interactions": stats[name]["interactions"],
            "Hit Dev.":  df1['dev_hit'].mean(),
            "NDCG Dev.": df1['dev_ndcg'].mean(),
            "CI-length": df1['CI_length'].mean(),
            "Sparsity": stats[name]["density"],
        }, ignore_index=True)

    # Output the final DataFrame
    print(data.to_latex(index=False))

devhit = lambda df: round(df[df['encoding'].isin([r'\None', r'\RotatoryCon', r'\RMHA'])]["dev_hit"].mean(), 4)
devndcg = lambda df: round(df[df['encoding'].isin([r'\None', r'\RotatoryCon', r'\RMHA'])]["dev_ndcg"].mean(), 4)
whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))

def greate_tables(list_df, stats):
    """ Compute the statistics and print them in latex format to be used ta the paper. """
    # This function is split into games and not because of the nan values in the norm maximum.
    list_df = [(df["dataset"][0], df) for df in list_df]
    list_games = [(name, df[df["nmax"].isna()]) for (name, df) in list_df if "game" in name]
    
    for case in [list_df, list_games]:
        print("########### STATISTICS 1")
        for (name, df1) in case:
            print(f" Dataset {name}, Hit dev total: {devhit(df1)}, NDCG dev total: {devndcg(df1)}")
        print("\n")
        print("########### STATISTICS 2")
        density_table(case, stats)
    
        print("########### all the tables")
        for (name, df1) in case:
            print(name)
            whole(df1)
        print("\n")
        print("########### max 3")
        for (name, df1) in case:
            print(name)
            show(df1, 3)
        print("\n")
        print("########### max 12")
        for (name, df1) in case:
            print(name)
            show(df1, 12)

In [7]:
round(dfsubgames[dfsubgames['encoding'].isin([r'\None'])]["dev_ndcg"].mean(), 4)

0.9217

In [8]:
greate_tables([dfsubmen, dfsubmen2, dfsubgames, dfsubfashion], stats)

########### STATISTICS 1
 Dataset Submen, Hit dev total: 6.2958, NDCG dev total: 7.9517
 Dataset Submen2, Hit dev total: 5.8036, NDCG dev total: 7.4573
 Dataset Subgames, Hit dev total: 1.3261, NDCG dev total: 0.95
 Dataset Subfashion, Hit dev total: 15.9992, NDCG dev total: 19.0358


########### STATISTICS 2

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:47: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append({
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:47: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append({
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:47: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append({
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:47: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append({
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:59: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(data.to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:63: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:63: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:63: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:63: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))

\begin{tabular}{llllllll}
\toprule
   Dataset & Users & Items & Interactions &  Hit Dev. & NDCG Dev. & CI-length &            Sparsity \\
\midrule
    Submen &  8332 & 10000 &        28603 &    7.2925 &    9.0925 &    10.515 &  \$2.860 times 10 4\$ \\
   Submen2 & 10000 & 45129 &        74391 &    5.1975 &    6.8225 &      8.31 &   1.648 times 10 4\$ \\
  Subgames &  5000 &  4601 &        33353 &  1.393333 &  0.921667 &      2.23 & \$1.3341 times 10 3\$ \\
Subfashion &  3840 &  5000 &        16080 &    15.105 &    17.935 &    24.175 &  \$3.564 times 10 4\$ \\
\bottomrule
\end{tabular}

########### all the tables
Submen
\begin{tabular}{llrrrrrrlr}
\toprule
activation &     encoding &   nmax &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg &  runs &             CI &  CI\_length \\
\midrule
     leaky &        \textbackslash None & 0.0001 &     77.10 &     3.72 &      67.89 &      5.25 &    12 &   (75.0, 79.2) &       4.20 \\
      silu &        \textbackslash None & 0.0001 &     76.33 &     6.11 &      67.00 &      7.08 &    12 & (72.87, 79.79) &       6.92 \\
     leaky &        \textbackslash None & 0.1000 &     69.29 &    15.21 &      58.64 &     18.19 &     6 & (57.12, 81.46) &      24.34 \\
      silu &        \textbackslash None & 0.1000 &     74.66 &     4.13 &      64.38 &      5.85 &     6 & (71.36, 77.96) &       6.60 \\
     leaky & \textbackslash RotatoryCon & 0.0001 &     71.82 &    11.90 &      61.69 &     14.11 &    12 & (65.09, 78.55) &      13.46 \\
      silu & \textbackslash RotatoryCon & 0.0001 &     75.28 &     3.63 &      65.31 &      5.03 &    12 & (73.23, 77.33) &       4.10 \\
     leaky & \textbackslash RotatoryCon & 0.1000 &     73.93 &     5.87 &      63.77 &      8.00 &     6 & (69.23, 78.63) &       9.40 \\
      silu & \textbackslash RotatoryCon & 0.1000 &     73.11 &     5.43 &      62.64 &      6.80 &     6 & (68.77, 77.45) &       8.68 \\
     leaky &        \textbackslash RMHA & 0.0001 &     75.96 &     2.71 &      66.03 &      4.00 &     8 & (74.08, 77.84) &       3.76 \\
      silu &        \textbackslash RMHA & 0.0001 &     70.44 &     9.61 &      59.67 &     11.50 &     8 &  (63.78, 77.1) &      13.32 \\
     leaky &        \textbackslash RMHA & 0.1000 &     77.28 &     2.66 &      68.45 &      3.65 &     6 & (75.15, 79.41) &       4.26 \\
      silu &        \textbackslash RMHA & 0.1000 &     72.54 &     4.57 &      61.75 &      5.96 &     6 &  (68.88, 76.2) &       7.32 \\
\bottomrule
\end{tabular}

Submen2
\begin{tabular}{llrrrrrrlr}
\toprule
activation &     encoding &   nmax &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg &  runs &             CI &  CI\_length \\
\midrule
     leaky &        \textbackslash None & 0.0001 &     72.08 &     6.04 &      61.47 &      7.96 &     6 & (67.25, 76.91) &       9.66 \\
      silu &        \textbackslash None & 0.0001 &     73.95 &     3.33 &      64.05 &      4.71 &     6 & (71.29, 76.61) &       5.32 \\
     leaky &        \textbackslash None & 0.1000 &     71.56 &     5.38 &      60.96 &      6.93 &     6 & (67.26, 75.86) &       8.60 \\
      silu &        \textbackslash None & 0.1000 &     70.51 &     6.04 &      59.29 &      7.69 &     6 & (65.68, 75.34) &       9.66 \\
     leaky & \textbackslash RotatoryCon & 0.0001 &     71.52 &     6.39 &      60.71 &      8.17 &     6 & (66.41, 76.63) &      10.22 \\
      silu & \textbackslash RotatoryCon & 0.0001 &     72.77 &     2.96 &      62.56 &      4.31 &     6 &  (70.4, 75.14) &       4.74 \\
     leaky & \textbackslash RotatoryCon & 0.1000 &     73.12 &     2.38 &      62.86 &      2.99 &     6 & (71.22, 75.02) &       3.80 \\
      silu & \textbackslash RotatoryCon & 0.1000 &     72.03 &     3.90 &      61.33 &      4.76 &     6 & (68.91, 75.15) &       6.24 \\
      silu &        \textbackslash RMHA & 0.0001 &     53.67 &     8.81 &      36.15 &     12.73 &    12 & (48.69, 58.65) &       9.96 \\
     leaky &        \textbackslash RMHA & 0.1000 &     61.82 &    12.74 &      48.93 &     14.82 &     6 & (51.63, 72.01) &      20.38 \\
      silu &        \textbackslash RMHA & 0.1000 &     61.27 &     5.87 &      47.24 &      6.96 &     6 & (56.57, 65.97) &       9.40 \\
\bottomrule
\end{tabular}

Subgames
\begin{tabular}{llrrrrrrlr}
\toprule
activation &     encoding &   nmax &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg &  runs &             CI &  CI\_length \\
\midrule
     leaky &        \textbackslash None & 0.0001 &     46.46 &     2.43 &      24.78 &      1.19 &     6 &  (44.52, 48.4) &       3.88 \\
      silu &        \textbackslash None & 0.0001 &     44.72 &     2.58 &      23.52 &      1.61 &     6 & (42.66, 46.78) &       4.12 \\
     leaky &        \textbackslash None & 0.1000 &     62.05 &     0.67 &      37.50 &      0.60 &     6 & (61.51, 62.59) &       1.08 \\
      silu &        \textbackslash None & 0.1000 &     62.58 &     0.45 &      37.82 &      0.58 &     6 & (62.22, 62.94) &       0.72 \\
     leaky &        \textbackslash None &    NaN &     49.53 &     1.01 &      28.84 &      0.69 &     6 & (48.72, 50.34) &       1.62 \\
      silu &        \textbackslash None &    NaN &     48.31 &     1.22 &      28.36 &      0.86 &     6 & (47.33, 49.29) &       1.96 \\
     leaky & \textbackslash RotatoryCon & 0.0001 &     55.07 &     1.91 &      30.45 &      1.89 &     6 &  (53.54, 56.6) &       3.06 \\
      silu & \textbackslash RotatoryCon & 0.0001 &     54.56 &     1.74 &      30.08 &      1.45 &     6 & (53.17, 55.95) &       2.78 \\
     leaky & \textbackslash RotatoryCon & 0.1000 &     61.10 &     0.51 &      36.98 &      0.35 &     6 & (60.69, 61.51) &       0.82 \\
      silu & \textbackslash RotatoryCon & 0.1000 &     61.00 &     0.77 &      37.14 &      0.60 &     6 & (60.38, 61.62) &       1.24 \\
     leaky & \textbackslash RotatoryCon &    NaN &     52.23 &     1.57 &      31.51 &      0.96 &     6 & (50.97, 53.49) &       2.52 \\
      silu & \textbackslash RotatoryCon &    NaN &     50.73 &     0.89 &      30.48 &      0.72 &     6 & (50.02, 51.44) &       1.42 \\
     leaky &        \textbackslash RMHA & 0.0001 &     46.54 &     1.89 &      24.62 &      1.16 &     6 & (45.03, 48.05) &       3.02 \\
      silu &        \textbackslash RMHA & 0.0001 &     41.13 &     2.46 &      22.05 &      1.60 &     6 &  (39.16, 43.1) &       3.94 \\
     leaky &        \textbackslash RMHA & 0.1000 &     62.34 &     0.63 &      38.41 &      0.29 &     6 & (61.84, 62.84) &       1.00 \\
      silu &        \textbackslash RMHA & 0.1000 &     63.06 &     0.84 &      39.15 &      0.89 &     6 & (62.39, 63.73) &       1.34 \\
     leaky &        \textbackslash RMHA &    NaN &     50.43 &     0.95 &      29.96 &      0.87 &     6 & (49.67, 51.19) &       1.52 \\
      silu &        \textbackslash RMHA &    NaN &     48.97 &     1.35 &      28.57 &      0.79 &     6 & (47.89, 50.05) &       2.16 \\
\bottomrule
\end{tabular}

Subfashion
\begin{tabular}{llrrrrrrlr}
\toprule
activation &     encoding &   nmax &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg &  runs &             CI &  CI\_length \\
\midrule
     leaky &        \textbackslash None & 0.0001 &     48.00 &    22.19 &      33.53 &     26.31 &     6 & (30.24, 65.76) &      35.52 \\
      silu &        \textbackslash None & 0.0001 &     66.30 &    18.61 &      55.17 &     21.99 &     6 & (51.41, 81.19) &      29.78 \\
     leaky &        \textbackslash None & 0.1000 &     32.94 &     1.89 &      16.77 &      3.00 &     6 & (31.43, 34.45) &       3.02 \\
      silu &        \textbackslash None & 0.1000 &     63.85 &    17.73 &      52.02 &     20.44 &     6 & (49.66, 78.04) &      28.38 \\
     leaky & \textbackslash RotatoryCon & 0.0001 &     50.04 &    19.62 &      35.82 &     22.95 &     6 & (34.34, 65.74) &      31.40 \\
      silu & \textbackslash RotatoryCon & 0.0001 &     63.87 &    19.99 &      52.59 &     22.77 &     6 & (47.87, 79.87) &      32.00 \\
     leaky & \textbackslash RotatoryCon & 0.1000 &     49.17 &    21.02 &      35.89 &     25.10 &     6 & (32.35, 65.99) &      33.64 \\
      silu & \textbackslash RotatoryCon & 0.1000 &     67.94 &    19.26 &      57.24 &     23.51 &     6 & (52.53, 83.35) &      30.82 \\
     leaky &        \textbackslash RMHA & 0.0001 &     79.72 &     2.85 &      71.57 &      3.66 &     6 &  (77.44, 82.0) &       4.56 \\
      silu &        \textbackslash RMHA & 0.0001 &     46.55 &    14.12 &      31.68 &     16.59 &     6 & (35.25, 57.85) &      22.60 \\
     leaky &        \textbackslash RMHA & 0.1000 &     57.99 &    20.07 &      45.36 &     24.01 &     6 & (41.93, 74.05) &      32.12 \\
      silu &        \textbackslash RMHA & 0.1000 &     61.14 &    14.64 &      48.46 &     18.10 &     6 & (49.43, 72.85) &      23.42 \\
\bottomrule
\end{tabular}



########### max 3
Submen
\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation & encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
 Submen &      leaky &    \textbackslash RMHA & 0.1000 &    2.0 &     77.28 &     2.66 &      68.45 &      3.65 \\
 Submen &      leaky &    \textbackslash RMHA & 0.0001 &    2.0 &     75.96 &     2.71 &      66.03 &      4.00 \\
\bottomrule
\end{tabular}

Submen2
\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation &     encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Submen2 &      leaky & \textbackslash RotatoryCon & 0.1000 &    2.0 &     73.12 &     2.38 &      62.86 &      2.99 \\
Submen2 &       silu & \textbackslash RotatoryCon & 0.0001 &    2.0 &     72.77 &     2.96 &      62.56 &      4.31 \\
\bottomrule
\end{tabular}

Subgames
\begin{tabular}{lllrrrrrr}
\toprule
 dataset & activation & encoding &  nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subgames &       silu &    \textbackslash RMHA &   0.1 &    2.0 &     63.06 &     0.84 &      39.15 &      0.89 \\
Subgames &       silu &    \textbackslash None &   0.1 &    2.0 &     62.58 &     0.45 &      37.82 &      0.58 \\
Subgames &      leaky &    \textbackslash RMHA &   0.1 &    2.0 &     62.34 &     0.63 &      38.41 &      0.29 \\
Subgames &      leaky &    \textbackslash None &   0.1 &    2.0 &     62.05 &     0.67 &      37.50 &      0.60 \\
\bottomrule
\end{tabular}

Subfashion

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:47: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append({
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:59: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(data.to_latex(index=False))

\begin{tabular}{lllrrrrrr}
\toprule
   dataset & activation & encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subfashion &      leaky &    \textbackslash RMHA & 0.0001 &    2.0 &     79.72 &     2.85 &      71.57 &      3.66 \\
Subfashion &      leaky &    \textbackslash None & 0.1000 &    2.0 &     32.94 &     1.89 &      16.77 &      3.00 \\
\bottomrule
\end{tabular}



########### max 12
Submen
\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation & encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
 Submen &      leaky &    \textbackslash RMHA & 0.1000 &    2.0 &     77.28 &     2.66 &      68.45 &      3.65 \\
 Submen &      leaky &    \textbackslash None & 0.0001 &    2.0 &     77.10 &     3.72 &      67.89 &      5.25 \\
 Submen &       silu &    \textbackslash None & 0.0001 &    2.0 &     76.33 &     6.11 &      67.00 &      7.08 \\
 Submen &      leaky &    \textbackslash RMHA & 0.0001 &    2.0 &     75.96 &     2.71 &      66.03 &      4.00 \\
\bottomrule
\end{tabular}

Submen2
\begin{tabular}{lllrrrrrr}
\toprule
dataset & activation &     encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Submen2 &       silu &        \textbackslash None & 0.0001 &    2.0 &     73.95 &     3.33 &      64.05 &      4.71 \\
Submen2 &      leaky & \textbackslash RotatoryCon & 0.1000 &    2.0 &     73.12 &     2.38 &      62.86 &      2.99 \\
Submen2 &       silu & \textbackslash RotatoryCon & 0.0001 &    2.0 &     72.77 &     2.96 &      62.56 &      4.31 \\
Submen2 &      leaky &        \textbackslash None & 0.0001 &    2.0 &     72.08 &     6.04 &      61.47 &      7.96 \\
\bottomrule
\end{tabular}

Subgames
\begin{tabular}{lllrrrrrr}
\toprule
 dataset & activation & encoding &  nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subgames &       silu &    \textbackslash RMHA &   0.1 &    2.0 &     63.06 &     0.84 &      39.15 &      0.89 \\
Subgames &       silu &    \textbackslash None &   0.1 &    2.0 &     62.58 &     0.45 &      37.82 &      0.58 \\
Subgames &      leaky &    \textbackslash RMHA &   0.1 &    2.0 &     62.34 &     0.63 &      38.41 &      0.29 \\
Subgames &      leaky &    \textbackslash None &   0.1 &    2.0 &     62.05 &     0.67 &      37.50 &      0.60 \\
\bottomrule
\end{tabular}

Subfashion
\begin{tabular}{lllrrrrrr}
\toprule
   dataset & activation & encoding &   nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subfashion &      leaky &    \textbackslash RMHA & 0.0001 &    2.0 &     79.72 &     2.85 &      71.57 &      3.66 \\
Subfashion &      leaky &    \textbackslash None & 0.1000 &    2.0 &     32.94 &     1.89 &      16.77 &      3.00 \\
\bottomrule
\end{tabular}

########### STATISTICS 1
 Dataset Subgames, Hit dev total: 1.165, NDCG dev total: 0.815


########### STATISTICS 2
\begin{tabular}{llllllll}
\toprule
 Dataset & Users & Items & Interactions & Hit Dev. & NDCG Dev. & CI-length &            Sparsity \\
\midrule
Subgames &  5000 &  4601 &        33353 &    1.115 &     0.775 &      1.79 & \$1.3341 times 10 3\$ \\
\bottomrule
\end{tabular}

########### all the tables
Subgames
\begin{tabular}{llrrrrrrlr}
\toprule
activation &     encoding &  nmax &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg &  runs &             CI &  CI\_length \\
\midrule
     leaky &        \textbackslash None &   NaN &     49.53 &     1.01 &      28.84 &      0.69 &     6 & (48.72, 50.34) &       1.62 \\
      silu &        \textbackslash None &   NaN &     48.31 &     1.22 &      28.36 &      0.86 &     6 & (47.33, 49.29) &       1.96 \\
     leaky & \textbackslash RotatoryCon &   NaN &     52.23 &     1.57 &      31.51 &      0.96 &     6 & (50.97, 53.49) &       2.52 \\
      silu & \textbackslash RotatoryCon &   NaN &     50.73 &     0.89 &      30.48 &      0.72 &     6 & (50.02, 51.44) &       1.42 \\
     leaky &        \textbackslash RMHA &   NaN &     50.43 &     0.95 &      29.96 &      0.87 &     6 & (49.67, 51.19) &       1.52 \\
      silu &        \textbackslash RMHA &   NaN &     48.97 &     1.35 &      28.57 &      0.79 &     6 & (47.89, 50.05) &       2.16 \\
\bottomrule
\end{tabular}



########### max 3
Subgames
\begin{tabular}{lllrrrrrr}
\toprule
 dataset & activation &     encoding &  nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subgames &      leaky & \textbackslash RotatoryCon &   NaN &    2.0 &     52.23 &     1.57 &      31.51 &      0.96 \\
Subgames &       silu & \textbackslash RotatoryCon &   NaN &    2.0 &     50.73 &     0.89 &      30.48 &      0.72 \\
Subgames &      leaky &        \textbackslash RMHA &   NaN &    2.0 &     50.43 &     0.95 &      29.96 &      0.87 \\
Subgames &      leaky &        \textbackslash None &   NaN &    2.0 &     49.53 &     1.01 &      28.84 &      0.69 \\
\bottomrule
\end{tabular}



########### max 12
Subgames
\begin{tabular}{lllrrrrrr}
\toprule
 dataset & activation &     encoding &  nmax &  ntype &  mean\_hit &  dev\_hit &  mean\_ndcg &  dev\_ndcg \\
\midrule
Subgames &      leaky & \textbackslash RotatoryCon &   NaN &    2.0 &     52.23 &     1.57 &      31.51 &      0.96 \\
Subgames &       silu & \textbackslash RotatoryCon &   NaN &    2.0 &     50.73 &     0.89 &      30.48 &      0.72 \\
Subgames &      leaky &        \textbackslash RMHA &   NaN &    2.0 &     50.43 &     0.95 &      29.96 &      0.87 \\
Subgames &      leaky &        \textbackslash None &   NaN &    2.0 &     49.53 &     1.01 &      28.84 &      0.69 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:63: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  whole = lambda df: print(cleanit_for_position(df).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_12252\3013030486.py:64: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  show = lambda df, num: print(best(df[mylist], num).head(4).to_latex(index=False))

In [2]:
dfnewdeal = print_it("newdeal", start=0)
dfnewdeal = renamer(dfnewdeal)
apply_min = True # min number of 2 runs
No_nan = False # If true ignore nan cases
encoding = True # If encoding onl metrics L2
pseudo = False # If pseudo only different of L2
add_confidence = True
nosas = True
max_apply = [0.0001, 0.1]
dfnewdeal = filter_dataframe(dfnewdeal, apply_min, No_nan, encoding, pseudo, nosas, 'newdeal', 
                            add_confidence, max_apply=max_apply)

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True

# P-values

In [26]:
from scipy.stats import ttest_1samp

# Assuming 'data' is a NumPy array or a list containing your performance measurements
reference_value = 0.550  # The value you want to compare against
data = np.array([42.5, 59.53, 43.11, 35.72, 63.72, 34.86])

# Perform one-sample t-test
t_stat, p_value = ttest_1samp(data, reference_value)

# Check if the p-value is less than the significance level (e.g., 0.05)
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. The mean performance is significantly different.")
else:
    print("Fail to reject the null hypothesis. The mean performance is not significantly different.")
p_value

Reject the null hypothesis. The mean performance is significantly different.

In [5]:
# Define the threshold value
threshold_value = 70

# Highlight entries equal or higher than the threshold
def highlight_greater_or_equal(val):
    return 'background-color: grey' if val >= threshold_value else ''

# Specify the columns you want to apply the styling to
columns_to_style = ['mean_hit', 'mean_ndcg']

# Apply the function to the specified columns
styled_df = dfmen[condition].style.applymap(highlight_greater_or_equal, subset=pd.IndexSlice[:, columns_to_style])


# Display the styled DataFrame
styled_df