In [1]:
from results_analysis import *
mylist = ["dataset", "activation","encoding","nmax", "ntype","mean_hit","dev_hit","mean_ndcg","dev_ndcg"]
mylist_all = ["activation","encoding","nmax","mean_hit","dev_hit","mean_ndcg","dev_ndcg"]
pd.set_option('display.max_rows', None)

## List all the trainings of a folder

In [2]:
# # dfgames_what = print_it("games_what", start=0)
# ##################
# dfgames = print_it("games", start=0)
# dfmen = print_it("men", start=0)
# dfbeauty = print_it("beauty", start=0)
# dffashion = print_it("fashion", start=0)
# # ################
dfsubmen = print_it("submen", start=0)
dfsubfashion = print_it("subfashion", start=0)
dfsubgames = print_it("subgames", start=0)
dfsubmen2 = print_it("submen2", start=0)

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True

Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True

Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True

Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
The trainings are coherent? True

The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
Difference at max_norm:  nan nan
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True
The trainings are coherent? True

In [3]:
# dfgames = renamer2(dfgames)
# dfbeauty = renamer2(dfbeauty)
# dffashion = renamer2(dffashion)
# dfmen = renamer2(dfmen)
######################
dfsubmen = renamer2(dfsubmen)
dfsubfashion = renamer2(dfsubfashion)
dfsubgames = renamer2(dfsubgames)
dfsubmen2 = renamer2(dfsubmen2)

In [4]:
# dfgames['encoding'] = dfgames['encoding'].apply(lambda x: x.replace('\\', ''))
# dfbeauty['encoding'] = dfbeauty['encoding'].apply(lambda x: x.replace('\\', ''))
# dffashion['encoding'] = dffashion['encoding'].apply(lambda x: x.replace('\\', ''))
# dfmen['encoding'] = dfmen['encoding'].apply(lambda x: x.replace('\\', ''))
######################
dfsubmen['encoding'] = dfsubmen['encoding'].apply(lambda x: x.replace('\\', ''))
dfsubfashion['encoding'] = dfsubfashion['encoding'].apply(lambda x: x.replace('\\', ''))
dfsubgames['encoding'] = dfsubgames['encoding'].apply(lambda x: x.replace('\\', ''))
dfsubmen2['encoding'] = dfsubmen2['encoding'].apply(lambda x: x.replace('\\', ''))

## Filtering

In [5]:
my_list_dfs = []

In [6]:
# import numpy as np
# apply_min = True # min number of 2 runs
# No_nan = False # If true ignore nan cases
# add_confidence = True
# nosas = True
# max_apply = [1.e-04, 5.e-01, 1.e-01, 1.e+00] 
# ntype_apply = [1.e-04, 1.e-02, 1.e-01, 1.e+00, 2.0]

# ###########################################################################
# encoding = False # If encoding only metrics L2
# pseudo = True # If pseudo only different of L2

# dfmen_ps = filter_dataframe(dfmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                             'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dfgames_ps = filter_dataframe(dfgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                               'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
# dfbeauty_ps = filter_dataframe(dfbeauty.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dffashion_ps = filter_dataframe(dffashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                 'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)

# ###########################################################################
# encoding = True # If encoding onl metrics L2
# pseudo = False # If pseudo onl different of L2

# dfmen1 = filter_dataframe(dfmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                          'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dfgames1 = filter_dataframe(dfgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                            'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
# dfbeauty1 = filter_dataframe(dfbeauty.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                             'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dffashion1 = filter_dataframe(dffashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                              'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)

# ###########################################################################
# encoding = False # If encoding onl metrics L2
# pseudo = False # If pseudo onl different of L2

# dfmen_total = filter_dataframe(dfmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dfgames_total = filter_dataframe(dfgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                  'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
# dfbeauty_total = filter_dataframe(dfbeauty.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                   'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
# dffashion_total = filter_dataframe(dffashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
#                                    'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)

# my_list_dfs += [
#     dfmen_ps, dfgames_ps, dfbeauty_ps, dffashion_ps,
#     dfmen_total, dfgames_total, dfbeauty_total, dffashion_total,
#     dfmen1, dfgames1, dfbeauty1, dffashion1
# ]

In [7]:
import numpy as np
apply_min = True # min number of 2 runs
No_nan = False # If true ignore nan cases
add_confidence = True
nosas = True
max_apply = [1.e-04, 5.e-01, 1.e-01, 1.e+00] 
ntype_apply = [1.e-04, 1.e-02, 1.e-01, 1.e+00, 2.0]

###########################################################################
# max_apply=[0.0001, 0.1, np.nan]

# dfsubmen = filter_dataframe(dfsubmen, apply_min, No_nan, encoding, pseudo, nosas, 'submen', 
#                             add_confidence, max_apply=[0.0001, 0.1, np.nan])
# dfsubfashion = filter_dataframe(dfsubfashion, apply_min, No_nan, encoding, pseudo, nosas, 'subfashion', 
#                                 add_confidence, max_apply=[0.0001, 0.1, np.nan])
# dfsubgames = filter_dataframe(dfsubgames, apply_min, No_nan, encoding, pseudo, nosas, 'subgames', 
#                               add_confidence, max_apply=[0.0001, 0.1, np.nan])



###########################################################################
encoding = False # If encoding only metrics L2
pseudo = True # If pseudo only different of L2

dfsubmen_ps = filter_dataframe(dfsubmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                            'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubgames_ps = filter_dataframe(dfsubgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                              'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
dfsubmen2_ps = filter_dataframe(dfsubmen2.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                               'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubfashion_ps = filter_dataframe(dfsubfashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                                'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)

###########################################################################
encoding = True # If encoding onl metrics L2
pseudo = False # If pseudo onl different of L2

dfsubmen1 = filter_dataframe(dfsubmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                         'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubgames1 = filter_dataframe(dfsubgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                           'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
dfsubmen21 = filter_dataframe(dfsubmen2.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                            'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubfashion1 = filter_dataframe(dfsubfashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                             'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)

###########################################################################
encoding = False # If encoding onl metrics L2
pseudo = False # If pseudo onl different of L2

dfsubmen_total = filter_dataframe(dfsubmen.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                               'men', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubgames_total = filter_dataframe(dfsubgames.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                                 'games', add_confidence, max_apply=max_apply + [np.nan], ntype_apply=ntype_apply)
dfsubmen2_total = filter_dataframe(dfsubmen2.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                                  'beauty', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)
dfsubfashion_total = filter_dataframe(dfsubfashion.copy(), apply_min, No_nan, encoding, pseudo, nosas,
                                   'fashion', add_confidence, max_apply=max_apply, ntype_apply=ntype_apply)


my_list_dfs += [
    dfsubmen_ps, dfsubgames_ps, dfsubmen2_ps, dfsubfashion_ps,
    dfsubmen_total, dfsubgames_total, dfsubmen2_total, dfsubfashion_total,
    dfsubmen1, dfsubgames1, dfsubmen21, dfsubfashion1
]

In [8]:
for df in my_list_dfs:
    df['encoding'] = df['encoding'].apply(lambda x: x.replace('\\', ''))

## BESTS

In [33]:
best(dffashion1,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
29,silu,RMHA,0.0001,2.0,77.26,0.24,49.75,2.33,6,Fashion,"(77.07, 77.45)",0.38
21,silu,LongerRMHA,0.0001,2.0,77.00,0.48,49.40,0.54,6,Fashion,"(76.62, 77.38)",0.76
28,leaky,RMHA,0.0001,2.0,76.46,0.25,49.49,2.18,6,Fashion,"(76.26, 76.66)",0.40
20,leaky,LongerRMHA,0.0001,2.0,76.20,0.51,49.85,3.92,6,Fashion,"(75.79, 76.61)",0.82
23,silu,LongRotatory,0.0001,2.0,71.50,1.22,49.69,6.41,7,Fashion,"(70.6, 72.4)",1.80

In [34]:
best(dffashion_ps,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
39,silu,LearntCon,0.0001,1.00,77.86,0.44,48.94,0.66,6,Fashion,"(77.51, 78.21)",0.70
38,leaky,LearntCon,0.0001,1.00,76.55,0.74,47.85,0.68,6,Fashion,"(75.96, 77.14)",1.18
37,silu,LearntCon,0.0001,0.10,73.19,0.76,55.05,6.14,6,Fashion,"(72.58, 73.8)",1.22
36,leaky,LearntCon,0.0001,0.10,73.15,2.63,58.51,9.63,6,Fashion,"(71.05, 75.25)",4.20
59,silu,Abs,1.0000,0.01,73.00,0.19,51.08,5.34,6,Fashion,"(72.85, 73.15)",0.30

In [35]:
best(dfmen1,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
21,silu,LongerRMHA,0.0001,2.0,70.13,0.42,46.41,4.18,6,Men,"(69.79, 70.47)",0.68
29,silu,RMHA,0.0001,2.0,69.70,0.64,43.75,1.44,6,Men,"(69.19, 70.21)",1.02
2,leaky,None,0.1000,2.0,69.69,1.28,57.94,1.69,3,Men,"(68.24, 71.14)",2.90
20,leaky,LongerRMHA,0.0001,2.0,69.05,1.44,46.14,7.37,6,Men,"(67.9, 70.2)",2.30
28,leaky,RMHA,0.0001,2.0,68.65,0.48,43.24,0.35,6,Men,"(68.27, 69.03)",0.76

In [36]:
best(dfmen_ps,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
30,leaky,None,1.0000,1.00,72.44,2.96,61.71,3.79,6,Men,"(70.07, 74.81)",4.74
39,silu,LearntCon,0.0001,1.00,70.76,0.88,43.65,0.74,6,Men,"(70.06, 71.46)",1.40
38,leaky,LearntCon,0.0001,1.00,69.35,0.80,43.35,0.56,6,Men,"(68.71, 69.99)",1.28
45,silu,RotatoryCon,0.1000,0.10,65.49,1.54,45.87,7.50,6,Men,"(64.26, 66.72)",2.46
43,silu,AbsCon,0.1000,0.01,65.34,2.44,46.26,7.99,6,Men,"(63.39, 67.29)",3.90

In [37]:
best(dfbeauty1,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
35,silu,Rotatory,0.0001,2.0,61.72,1.14,42.54,1.52,5,Beauty,"(60.72, 62.72)",2.00
13,silu,RotatoryCon,0.0001,2.0,61.68,1.04,42.31,0.97,3,Beauty,"(60.5, 62.86)",2.36
12,leaky,RotatoryCon,0.0001,2.0,61.16,0.77,42.83,0.48,3,Beauty,"(60.29, 62.03)",1.74
34,leaky,Rotatory,0.0001,2.0,58.69,1.31,40.83,0.71,5,Beauty,"(57.54, 59.84)",2.30
1,silu,None,0.0001,2.0,57.03,0.83,38.42,0.68,9,Beauty,"(56.49, 57.57)",1.08

In [38]:
best(dfbeauty_ps,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
49,silu,RotatoryCon,0.5000,0.0001,62.85,0.14,44.21,0.30,3,Beauty,"(62.69, 63.01)",0.32
35,silu,None,0.0001,0.0100,62.84,0.64,43.97,0.26,3,Beauty,"(62.12, 63.56)",1.44
45,silu,RotatoryCon,0.1000,0.1000,62.83,0.57,43.99,0.47,3,Beauty,"(62.18, 63.48)",1.30
51,silu,RotatoryCon,0.5000,0.0100,62.75,0.72,43.78,0.98,3,Beauty,"(61.94, 63.56)",1.62
41,silu,AbsCon,0.1000,0.0001,62.71,0.80,44.13,1.18,3,Beauty,"(61.8, 63.62)",1.82

In [39]:
best(dfgames1,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
16,leaky,RotatoryCon,NaN,2.0,80.62,0.55,56.07,0.79,6,Games,"(80.18, 81.06)",0.88
31,silu,LongerconRotatory,NaN,2.0,80.29,0.47,55.18,0.55,6,Games,"(79.91, 80.67)",0.76
30,leaky,LongerconRotatory,NaN,2.0,80.21,1.51,55.06,1.93,6,Games,"(79.0, 81.42)",2.42
15,silu,RotatoryCon,0.1,2.0,80.17,1.03,56.29,1.53,5,Games,"(79.27, 81.07)",1.80
29,silu,Learnt,NaN,2.0,79.82,1.88,54.30,2.95,8,Games,"(78.52, 81.12)",2.60

In [40]:
best(dfgames_ps,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
66,leaky,RotatoryCon,1.0000,0.0100,81.52,0.61,56.99,1.21,6,Games,"(81.03, 82.01)",0.98
50,leaky,None,0.1000,0.0100,81.38,0.56,56.86,0.75,6,Games,"(80.93, 81.83)",0.90
64,leaky,RotatoryCon,1.0000,0.0001,81.25,0.84,56.77,1.13,6,Games,"(80.58, 81.92)",1.34
42,leaky,None,0.0001,0.0100,81.23,0.66,56.69,1.08,6,Games,"(80.7, 81.76)",1.06
74,leaky,RotatoryCon,NaN,0.0100,81.21,0.76,56.53,0.99,6,Games,"(80.6, 81.82)",1.22

In [41]:
best(dfgames_total,3).head(5)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
94,leaky,RotatoryCon,1.0000,0.0100,81.52,0.61,56.99,1.21,6,Games,"(81.03, 82.01)",0.98
74,leaky,RotatoryCon,0.1000,0.0100,81.38,0.56,56.86,0.75,6,Games,"(80.93, 81.83)",0.90
92,leaky,RotatoryCon,1.0000,0.0001,81.25,0.84,56.77,1.13,6,Games,"(80.58, 81.92)",1.34
62,leaky,RotatoryCon,0.0001,0.0100,81.23,0.66,56.69,1.08,6,Games,"(80.7, 81.76)",1.06
104,leaky,RotatoryCon,NaN,0.0100,81.21,0.76,56.53,0.99,6,Games,"(80.6, 81.82)",1.22

## CORRELATIONS STUDY

In [65]:
df1 =dfgames_total[dfgames_total['encoding'].isin(['RotatoryCon'])]
df1 = df1[['ntype', 'nmax', 'mean_hit', 'dev_hit', 'mean_ndcg','dev_ndcg']]
df = df1.groupby('ntype')
df.mean()

            nmax  mean_hit   dev_hit  mean_ndcg  dev_ndcg
ntype
0.0000  0.366700   74.6625  1.122500  50.125000  1.807500
0.0001  0.400025   80.2640  0.905000  55.500000  1.047000
0.0100  0.400025   80.5430  0.877000  55.790000  1.060000
0.1000  0.400025   80.4550  1.013000  55.771000  1.167000
1.0000  0.400025   78.4430  1.046000  54.484000  1.392000
2.0000  0.050050   78.5650  1.726667  54.336667  1.956667

In [66]:
df2 =dfgames_total[dfgames_total['encoding'].isin(['None'])]
df2 = df2[['ntype', 'nmax', 'mean_hit', 'dev_hit', 'mean_ndcg','dev_ndcg']]
df = df1.groupby('ntype')
df.mean()

            nmax  mean_hit   dev_hit  mean_ndcg  dev_ndcg
ntype
0.0000  0.366700   74.6625  1.122500  50.125000  1.807500
0.0001  0.400025   80.2640  0.905000  55.500000  1.047000
0.0100  0.400025   80.5430  0.877000  55.790000  1.060000
0.1000  0.400025   80.4550  1.013000  55.771000  1.167000
1.0000  0.400025   78.4430  1.046000  54.484000  1.392000
2.0000  0.050050   78.5650  1.726667  54.336667  1.956667

In [67]:
corr = df2.corr()
corr.style.background_gradient(cmap='coolwarm')

In [68]:
corr = df1.corr()
corr.style.background_gradient(cmap='coolwarm')

In [64]:
corr = dfgames_total.corr()
corr.style.background_gradient(cmap='coolwarm')

# COMPATIBILITY

In [10]:
# en1 = ['None', 'RotatoryCon']
# en2 = ['None', 'RMHA']
# cases = [(dfbeauty_ps, "beauty", en1), (dfgames_ps, "games", en1), (dfmen_ps, "men", en2), (dffashion_ps, "fashion", en2)]
# for df, data, encodings in cases:
#     print(f"dataset: {data}")
#     df = df[df['encoding'].isin(encodings)]
#     activations = df["activation"].unique()
#     nmax_values = df["nmax"].unique()
#     ntype_values = df["ntype"].unique()
#     print(f"nmax_values: {nmax_values}")
#     print(f"ntype_values: {ntype_values}")
#     print(f"activations: {activations}")
#     print(f"encodings: {encodings}")
#     check_combinations(df, activations, encodings, nmax_values, ntype_values)

In [9]:
en1 = ['None', 'RotatoryCon']
en2 = ['None', 'RMHA']
# (dfsubgames_ps, "subgames", en1)
cases = [(dfsubgames_total, "subgames", en1), (dfsubmen_total, "submen", en2), (dfsubmen2_total, "submen2", en1), (dfsubfashion_total, "subfashion", en2)]
for df, data, encodings in cases:
    print(f"Dataset: {data}")
    activations = df["activation"].unique()
    nmax_values = [1.e-04, 1.e-01, 5.e-01, 1.e+00] 
    nmax_values += [np.nan] if "games" in data else []
    ntype_values = [1.e-04, 1.e-02, 1.e-01, 1.e+00, 2.e+00]  #  df["ntype"].unique()
    print(f"encodings: {encodings}")
    print(f"ntype_values: {ntype_values}")
    print(f"nmax_values: {nmax_values}")
    check_combinations(df, activations, encodings, nmax_values, [1.e-04,1.e-02, 1.e-01, 1.e+00, 2.e+00])

Dataset: subgames
encodings: ['None', 'RotatoryCon']
ntype_values: [0.0001, 0.01, 0.1, 1.0, 2.0]
nmax_values: [0.0001, 0.1, 0.5, 1.0, nan]
All combinations are included in the DataFrame.
Dataset: submen
encodings: ['None', 'RMHA']
ntype_values: [0.0001, 0.01, 0.1, 1.0, 2.0]
nmax_values: [0.0001, 0.1, 0.5, 1.0]
All combinations are included in the DataFrame.
Dataset: submen2
encodings: ['None', 'RotatoryCon']
ntype_values: [0.0001, 0.01, 0.1, 1.0, 2.0]
nmax_values: [0.0001, 0.1, 0.5, 1.0]
All combinations are included in the DataFrame.
Dataset: subfashion
encodings: ['None', 'RMHA']
ntype_values: [0.0001, 0.01, 0.1, 1.0, 2.0]
nmax_values: [0.0001, 0.1, 0.5, 1.0]
All combinations are included in the DataFrame.

# PSEUDO correlations

In [14]:
dfmen_partial = dfmen[dfmen['encoding'].isin(['carca', 'RMHA'])]
dffashion_partial = dffashion[dffashion['encoding'].isin(['carca', 'RMHA'])]
dfgames_partial = dfgames[dfgames['encoding'].isin(['carca', 'conRotatory'])]
dfbeauty_partial = dfbeauty[dfbeauty['encoding'].isin(['carca', 'conRotatory'])]

In [15]:
dfbeauty_ps.corr()

,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,CI_length
nmax,1.000000e+00,-5.259178e-18,-0.146784,-0.196653,-0.131174,-0.126283,0.153408,-0.218587
ntype,-5.259178e-18,1.000000e+00,-0.686913,0.243578,-0.660162,0.122856,0.080884,0.232002
mean_hit,-1.467836e-01,-6.869128e-01,1.000000,-0.218176,0.990845,-0.137953,0.012734,-0.220253
dev_hit,-1.966534e-01,2.435782e-01,-0.218176,1.000000,-0.228868,0.822079,0.090975,0.987662
mean_ndcg,-1.311745e-01,-6.601619e-01,0.990845,-0.228868,1.000000,-0.132758,0.045286,-0.236022
dev_ndcg,-1.262827e-01,1.228563e-01,-0.137953,0.822079,-0.132758,1.000000,0.189662,0.791602
runs,1.534078e-01,8.088445e-02,0.012734,0.090975,0.045286,0.189662,1.000000,-0.059157
CI_length,-2.185867e-01,2.320022e-01,-0.220253,0.987662,-0.236022,0.791602,-0.059157,1.000000

In [8]:
dfbeauty_ps.corr()['mean_hit'], dfbeauty_ps.corr()['mean_ndcg']

(nmax        -0.176664
 ntype       -0.686751
 mean_hit     1.000000
 dev_hit     -0.220571
 mean_ndcg    0.990775
 dev_ndcg    -0.139719
 runs        -0.059688
 CI_length   -0.215703
 Name: mean_hit, dtype: float64,
 nmax        -0.163498
 ntype       -0.660155
 mean_hit     0.990775
 dev_hit     -0.231742
 mean_ndcg    1.000000
 dev_ndcg    -0.134756
 runs        -0.027970
 CI_length   -0.231297
 Name: mean_ndcg, dtype: float64)

In [9]:
dffashion_ps.corr()['mean_hit'], dffashion_ps.corr()['mean_ndcg']

(nmax        -0.096465
 ntype       -0.229607
 mean_hit     1.000000
 dev_hit     -0.648361
 mean_ndcg    0.699838
 dev_ndcg    -0.505811
 runs        -0.316262
 CI_length   -0.605730
 Name: mean_hit, dtype: float64,
 nmax        -0.003797
 ntype       -0.390891
 mean_hit     0.699838
 dev_hit     -0.142928
 mean_ndcg    1.000000
 dev_ndcg    -0.073654
 runs        -0.132752
 CI_length   -0.117060
 Name: mean_ndcg, dtype: float64)

In [10]:
dfgames_ps.corr()['mean_hit'], dfgames_ps.corr()['mean_ndcg']

(nmax         0.237459
 ntype       -0.405851
 mean_hit     1.000000
 dev_hit     -0.470016
 mean_ndcg    0.956190
 dev_ndcg    -0.356787
 runs              NaN
 CI_length   -0.468916
 Name: mean_hit, dtype: float64,
 nmax         0.224524
 ntype       -0.256635
 mean_hit     0.956190
 dev_hit     -0.446484
 mean_ndcg    1.000000
 dev_ndcg    -0.263486
 runs              NaN
 CI_length   -0.445859
 Name: mean_ndcg, dtype: float64)

In [11]:
dfmen_ps.corr()['mean_hit'], dfmen_ps.corr()['mean_ndcg']

(nmax        -0.150405
 ntype       -0.355416
 mean_hit     1.000000
 dev_hit     -0.129586
 mean_ndcg    0.854786
 dev_ndcg    -0.165838
 runs        -0.073108
 CI_length   -0.148880
 Name: mean_hit, dtype: float64,
 nmax        -0.039371
 ntype       -0.403900
 mean_hit     0.854786
 dev_hit      0.171746
 mean_ndcg    1.000000
 dev_ndcg     0.073839
 runs         0.083805
 CI_length    0.170922
 Name: mean_ndcg, dtype: float64)

##  PSEUDO results

In [12]:
best(dfbeauty_ps[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
57,beauty,silu,conRotatory,0.5000,0.0001,62.85,0.14,44.21,0.30
43,beauty,silu,conRotatory,0.0001,0.0100,62.84,0.64,43.97,0.26
53,beauty,silu,conRotatory,0.1000,0.1000,62.83,0.57,43.99,0.47
59,beauty,silu,conRotatory,0.5000,0.0100,62.75,0.72,43.78,0.98

In [13]:
best(dfbeauty_ps[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
57,beauty,silu,conRotatory,0.5000,0.0001,62.85,0.14,44.21,0.30
43,beauty,silu,conRotatory,0.0001,0.0100,62.84,0.64,43.97,0.26
53,beauty,silu,conRotatory,0.1000,0.1000,62.83,0.57,43.99,0.47
59,beauty,silu,conRotatory,0.5000,0.0100,62.75,0.72,43.78,0.98

In [14]:
best(dfbeauty[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
49,beauty,leaky,AbsCon,0.0001,2.0,67.93,4.17,48.71,3.59
97,beauty,silu,Learnt,0.0001,2.0,67.62,6.95,46.33,7.08
101,beauty,silu,Abs,0.0001,2.0,67.27,10.59,45.34,10.75
50,beauty,silu,AbsCon,0.0001,2.0,65.87,5.23,45.61,5.12

In [16]:
best(dfbeauty[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
74,beauty,silu,conRotatory,0.5000,0.0001,62.85,0.14,44.21,0.30
56,beauty,silu,conRotatory,0.0001,0.0100,62.84,0.64,43.97,0.26
68,beauty,silu,conRotatory,0.1000,0.1000,62.83,0.57,43.99,0.47
76,beauty,silu,conRotatory,0.5000,0.0100,62.75,0.72,43.78,0.98

#### MEN

In [17]:
best(dfmen_ps[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
28,men,leaky,carca,1.0000,0.1000,72.77,5.14,61.96,6.65
30,men,leaky,carca,1.0000,1.0000,72.44,2.96,61.71,3.79
5,men,silu,carca,0.0001,0.1000,71.55,7.11,61.24,8.71
0,men,leaky,carca,0.0001,0.0001,71.42,7.11,60.75,9.22

In [18]:
best(dfmen_ps[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
30,men,leaky,carca,1.0000,1.0,72.44,2.96,61.71,3.79
39,men,silu,RMHA,0.0001,1.0,70.76,0.88,43.65,0.74
38,men,leaky,RMHA,0.0001,1.0,69.35,0.80,43.35,0.56
45,men,silu,RMHA,0.1000,0.1,65.49,1.54,45.87,7.50

In [19]:
best(dfmen[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
38,men,leaky,LearntCon,0.1000,2.0,73.86,7.18,58.89,8.15
32,men,leaky,carca,1.0000,0.1,72.77,5.14,61.96,6.65
34,men,leaky,carca,1.0000,1.0,72.44,2.96,61.71,3.79
48,men,leaky,Learnt,0.0001,2.0,72.08,4.44,56.55,9.98

In [20]:
best(dfmen[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
34,men,leaky,carca,1.0000,1.0,72.44,2.96,61.71,3.79
67,men,silu,RMHA,0.0001,1.0,70.76,0.88,43.65,0.74
53,men,silu,LongerRMHA,0.0001,2.0,70.13,0.42,46.41,4.18
69,men,silu,RMHA,0.0001,2.0,69.70,0.64,43.75,1.44

####  FASHION

In [21]:
best(dffashion_ps[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
53,fashion,silu,RMHA,0.0001,1.00,77.86,0.44,48.94,0.66
52,fashion,leaky,RMHA,0.0001,1.00,76.55,0.74,47.85,0.68
82,fashion,leaky,RMHA,NaN,0.10,73.78,2.26,61.05,8.63
64,fashion,leaky,RMHA,0.5000,0.01,73.72,3.30,62.94,4.83

In [22]:
best(dffashion_ps[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
53,fashion,silu,RMHA,0.0001,1.0,77.86,0.44,48.94,0.66
52,fashion,leaky,RMHA,0.0001,1.0,76.55,0.74,47.85,0.68
82,fashion,leaky,RMHA,NaN,0.1,73.78,2.26,61.05,8.63
35,fashion,leaky,carca,NaN,0.1,73.49,1.44,63.71,1.72

In [25]:
best(dffashion[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
81,fashion,silu,RMHA,0.0001,1.0,77.86,0.44,48.94,0.66
83,fashion,silu,RMHA,0.0001,2.0,77.26,0.24,49.75,2.33
67,fashion,silu,LongerRMHA,0.0001,2.0,77.00,0.48,49.40,0.54
80,fashion,leaky,RMHA,0.0001,1.0,76.55,0.74,47.85,0.68

In [26]:
best(dffashion[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
81,fashion,silu,RMHA,0.0001,1.0,77.86,0.44,48.94,0.66
83,fashion,silu,RMHA,0.0001,2.0,77.26,0.24,49.75,2.33
67,fashion,silu,LongerRMHA,0.0001,2.0,77.00,0.48,49.40,0.54
80,fashion,leaky,RMHA,0.0001,1.0,76.55,0.74,47.85,0.68

#### GAMES

In [27]:
best(dfgames_ps[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
66,games,leaky,conRotatory,1.0000,0.0100,81.52,0.61,56.99,1.21
50,games,leaky,conRotatory,0.1000,0.0100,81.38,0.56,56.86,0.75
64,games,leaky,conRotatory,1.0000,0.0001,81.25,0.84,56.77,1.13
42,games,leaky,conRotatory,0.0001,0.0100,81.23,0.66,56.69,1.08

In [28]:
best(dfgames_ps[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
66,games,leaky,conRotatory,1.0000,0.0100,81.52,0.61,56.99,1.21
50,games,leaky,conRotatory,0.1000,0.0100,81.38,0.56,56.86,0.75
64,games,leaky,conRotatory,1.0000,0.0001,81.25,0.84,56.77,1.13
42,games,leaky,conRotatory,0.0001,0.0100,81.23,0.66,56.69,1.08

In [29]:
best(dfgames[mylist], 12).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
57,games,silu,LearntCon,0.1,2.00,84.84,7.39,60.31,5.38
122,games,leaky,Learnt,0.1,2.00,84.44,6.90,56.27,3.47
56,games,leaky,LearntCon,0.1,2.00,83.62,7.19,57.91,1.72
94,games,leaky,conRotatory,1.0,0.01,81.52,0.61,56.99,1.21

In [32]:
best(dfgames[mylist], 3).head(4)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg
94,games,leaky,conRotatory,1.0000,0.0100,81.52,0.61,56.99,1.21
74,games,leaky,conRotatory,0.1000,0.0100,81.38,0.56,56.86,0.75
92,games,leaky,conRotatory,1.0000,0.0001,81.25,0.84,56.77,1.13
62,games,leaky,conRotatory,0.0001,0.0100,81.23,0.66,56.69,1.08

In [33]:
dffashion[dffashion['ntype'] != 2.0].sort_values(by='mean_hit', ascending=False).head(4)

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,CI,CI_length
81,silu,RMHA,0.0001,1.00,77.86,0.44,48.94,0.66,6,fashion,"(77.51, 78.21)",0.70
80,leaky,RMHA,0.0001,1.00,76.55,0.74,47.85,0.68,6,fashion,"(75.96, 77.14)",1.18
114,leaky,RMHA,NaN,0.10,73.78,2.26,61.05,8.63,6,fashion,"(71.97, 75.59)",3.62
96,leaky,RMHA,0.5000,0.01,73.72,3.30,62.94,4.83,6,fashion,"(71.08, 76.36)",5.28

In [32]:
best(dfgames[mylist], 3).head(8)

,dataset,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs
66,games,leaky,conRotatory,1.0000,0.0100,81.52,0.61,56.99,1.21,6
50,games,leaky,conRotatory,0.1000,0.0100,81.38,0.56,56.86,0.75,6
64,games,leaky,conRotatory,1.0000,0.0001,81.25,0.84,56.77,1.13,6
42,games,leaky,conRotatory,0.0001,0.0100,81.23,0.66,56.69,1.08,6
74,games,leaky,conRotatory,NaN,0.0100,81.21,0.76,56.53,0.99,6
76,games,leaky,conRotatory,NaN,0.1000,81.02,0.80,56.65,0.92,6
78,games,leaky,conRotatory,NaN,1.0000,81.01,0.70,56.51,1.09,6
44,games,leaky,conRotatory,0.0001,0.1000,80.98,0.83,56.37,0.99,6

In [33]:
dfgames

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset
0,leaky,None,0.0001,0.0001,79.18,1.07,53.78,0.97,6,games
1,silu,None,0.0001,0.0001,77.82,1.11,52.24,0.95,6,games
2,leaky,None,0.0001,0.0100,78.78,1.29,53.31,1.06,6,games
3,silu,None,0.0001,0.0100,78.13,1.36,52.73,1.66,6,games
4,leaky,None,0.0001,0.1000,79.34,0.72,53.80,0.47,6,games
5,silu,None,0.0001,0.1000,77.41,1.55,52.11,1.29,6,games
6,leaky,None,0.0001,1.0000,71.80,1.52,43.75,1.59,6,games
7,silu,None,0.0001,1.0000,71.75,2.33,43.43,1.93,6,games
8,leaky,None,0.1000,0.0001,78.80,0.40,53.13,0.74,6,games
9,silu,None,0.1000,0.0001,78.93,0.44,53.42,0.59,6,games
10,leaky,None,0.1000,0.0100,79.02,0.38,53.58,0.57,6,games
11,silu,None,0.1000,0.0100,77.65,1.48,52.07,1.40,6,games
12,leaky,None,0.1000,0.1000,79.44,0.88,54.05,0.73,6,games
13,silu,None,0.1000,0.1000,78.24,1.09,52.98,1.28,6,games
14,leaky,None,0.1000,1.0000,78.94,1.27,53.51,1.40,6,games
15,silu,None,0.1000,1.0000,79.28,1.22,53.99,1.21,6,games
16,leaky,None,0.5000,0.0001,79.20,0.66,53.81,0.57,6,games
17,silu,None,0.5000,0.0001,77.66,1.20,52.25,1.45,6,games
18,leaky,None,0.5000,0.0100,78.77,1.06,53.15,0.91,6,games
19,silu,None,0.5000,0.0100,78.24,0.99,52.67,1.30,6,games
20,leaky,None,0.5000,0.1000,78.74,0.70,53.41,0.91,6,games
21,silu,None,0.5000,0.1000,78.60,0.67,53.02,0.74,6,games
22,leaky,None,0.5000,1.0000,77.11,1.51,52.18,1.82,6,games
23,silu,None,0.5000,1.0000,79.80,1.13,55.56,1.65,6,games
24,leaky,None,1.0000,0.0001,79.36,1.19,53.77,1.08,6,games
25,silu,None,1.0000,0.0001,78.33,1.81,52.69,1.58,6,games
26,leaky,None,1.0000,0.0100,79.17,0.71,53.77,0.73,6,games
27,silu,None,1.0000,0.0100,78.46,0.94,52.95,1.04,6,games
28,leaky,None,1.0000,0.1000,79.46,0.13,54.15,0.46,6,games
29,silu,None,1.0000,0.1000,78.46,0.88,52.92,0.81,6,games
30,leaky,None,1.0000,1.0000,77.90,1.29,53.20,1.81,6,games
31,silu,None,1.0000,1.0000,79.72,1.49,55.41,1.90,6,games
32,leaky,None,NaN,0.0001,79.74,0.87,54.16,1.02,6,games
33,silu,None,NaN,0.0001,78.65,1.23,53.14,1.18,6,games
34,leaky,None,NaN,0.0100,79.02,1.47,53.64,1.40,6,games
35,silu,None,NaN,0.0100,79.13,0.68,53.50,0.73,6,games
36,leaky,None,NaN,0.1000,79.01,1.40,53.56,1.66,6,games
37,silu,None,NaN,0.1000,77.79,0.25,52.29,0.44,6,games
38,leaky,None,NaN,1.0000,78.99,1.09,53.62,0.92,6,games
39,silu,None,NaN,1.0000,77.88,1.37,52.28,1.72,6,games
40,leaky,conRotatory,0.0001,0.0001,80.51,0.58,56.05,0.71,6,games
41,silu,conRotatory,0.0001,0.0001,79.50,1.14,54.52,1.37,6,games
42,leaky,conRotatory,0.0001,0.0100,81.23,0.66,56.69,1.08,6,games
43,silu,conRotatory,0.0001,0.0100,79.94,0.68,55.17,0.93,6,games
44,leaky,conRotatory,0.0001,0.1000,80.98,0.83,56.37,0.99,6,games
45,silu,conRotatory,0.0001,0.1000,80.82,1.25,56.01,1.41,6,games
46,leaky,conRotatory,0.0001,1.0000,73.71,0.93,50.37,1.25,6,games
47,silu,conRotatory,0.0001,1.0000,74.22,1.44,50.31,1.74,6,games
48,leaky,conRotatory,0.1000,0.0001,80.29,0.99,55.56,0.98,6,games
49,silu,conRotatory,0.1000,0.0001,79.92,1.51,54.92,1.71,6,games
50,leaky,conRotatory,0.1000,0.0100,81.38,0.56,56.86,0.75,6,games
51,silu,conRotatory,0.1000,0.0100,80.05,0.92,55.16,1.04,6,games
52,leaky,conRotatory,0.1000,0.1000,80.70,0.49,56.49,0.61,6,games
53,silu,conRotatory,0.1000,0.1000,80.01,0.92,54.83,0.85,6,games
54,leaky,conRotatory,0.1000,1.0000,78.19,2.11,54.82,2.35,6,games
55,silu,conRotatory,0.1000,1.0000,79.65,1.05,56.51,1.49,6,games
56,leaky,conRotatory,0.5000,0.0001,80.51,1.03,55.82,1.57,6,games
57,silu,conRotatory,0.5000,0.0001,79.89,0.99,54.97,1.13,6,games
58,leaky,conRotatory,0.5000,0.0100,80.17,0.86,55.50,0.88,6,games
59,silu,conRotatory,0.5000,0.0100,80.13,0.71,55.28,0.77,6,games
60,leaky,conRotatory,0.5000,0.1000,80.72,1.10,56.24,1.01,6,games
61,silu,conRotatory,0.5000,0.1000,80.25,1.00,55.23,1.36,6,games
62,leaky,conRotatory,0.5000,1.0000,78.83,0.93,54.34,1.43,6,games
63,silu,conRotatory,0.5000,1.0000,79.01,0.98,54.46,1.58,6,games
64,leaky,conRotatory,1.0000,0.0001,81.25,0.84,56.77,1.13,6,games
65,silu,conRotatory,1.0000,0.0001,80.19,0.73,55.04,0.84,6,games
66,leaky,conRotatory,1.0000,0.0100,81.52,0.61,56.99,1.21,6,games
67,silu,conRotatory,1.0000,0.0100,79.61,1.55,54.35,1.49,6,games
68,leaky,conRotatory,1.0000,0.1000,80.41,1.05,55.98,1.29,6,games
69,silu,conRotatory,1.0000,0.1000,79.77,1.35,54.92,1.66,6,games
70,leaky,conRotatory,1.0000,1.0000,79.86,0.45,55.71,0.70,6,games
71,silu,conRotatory,1.0000,1.0000,79.48,0.90,55.81,1.40,6,games
72,leaky,conRotatory,NaN,0.0001,80.33,0.54,56.03,0.48,6,games
73,silu,conRotatory,NaN,0.0001,80.25,0.70,55.32,0.55,6,games
74,leaky,conRotatory,NaN,0.0100,81.21,0.76,56.53,0.99,6,games
75,silu,conRotatory,NaN,0.0100,80.19,1.46,55.37,1.46,6,games
76,leaky,conRotatory,NaN,0.1000,81.02,0.80,56.65,0.92,6,games
77,silu,conRotatory,NaN,0.1000,79.87,1.34,54.99,1.57,6,games
78,leaky,conRotatory,NaN,1.0000,81.01,0.70,56.51,1.09,6,games
79,silu,conRotatory,NaN,1.0000,80.47,0.97,56.00,0.89,6,games

### DEVIATIONS

In [27]:
df = pd.concat([dffashion, dfbeauty, dfgames, dfmen])

In [33]:
df2 = cleanit(df)
df2 = df2[(df2['nmax'] == 0.0001) | (df2['nmax'].isna())]
grouped_df = df2.groupby('encoding')
mean_values = grouped_df.mean()
mean_values = mean_values.round(2)
print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

\begin{tabular}{lrrrr}
\toprule
{} &  dev\_hit &  dev\_ndcg &  runs &  CI-length \\
encoding        &          &           &       &            \\
\midrule
Abs             &     5.43 &      8.25 &  9.38 &       6.71 \\
AbsCon          &     3.52 &      5.56 &  7.12 &       5.35 \\
Learnt          &     4.79 &      7.64 &  7.88 &       7.05 \\
LearntCon       &     3.17 &      6.36 &  6.62 &       4.42 \\
LongROPEMHA     &     3.33 &      8.15 &  5.25 &       5.99 \\
LongRotatory    &     1.05 &      1.04 &  4.67 &       2.08 \\
LongRotatoryCon &     0.99 &      1.24 &  6.00 &       1.59 \\
LongerRMHA      &     0.71 &      4.00 &  6.00 &       1.14 \\
None            &     2.35 &      5.26 &  8.00 &       3.29 \\
RMHA            &     0.51 &      1.08 &  6.00 &       0.88 \\
RMHAROPEONE     &     2.82 &      6.54 &  4.29 &       5.46 \\
ROPEMHA         &     2.38 &      5.45 &  5.00 &       4.04 \\
Rotatory        &     2.46 &      5.01 &  8.38 &       3.48 \\
RotatoryCon     &     2.48 &      5.18 &  6.75 &       3.49 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12408\2684527896.py:6: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

In [34]:
df3 = cleanit(df)
# df2 = df2[(df2['nmax'] == 0.0001) | (df2['nmax'].isna())]
grouped_df = df3.groupby('encoding')
mean_values = grouped_df.mean()
mean_values = mean_values.round(2)
print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

\begin{tabular}{lrrrr}
\toprule
{} &  dev\_hit &  dev\_ndcg &   runs &  CI-length \\
encoding        &          &           &        &            \\
\midrule
Abs             &     7.20 &      9.42 &  10.57 &       8.42 \\
AbsCon          &     4.67 &      6.58 &   8.00 &       6.36 \\
Learnt          &     7.43 &      9.98 &   9.07 &      10.17 \\
LearntCon       &     4.09 &      6.53 &   6.93 &       5.66 \\
LongROPEMHA     &     3.33 &      8.15 &   5.25 &       5.99 \\
LongRotatory    &     1.31 &      1.35 &   4.00 &       3.00 \\
LongRotatoryCon &     0.99 &      1.24 &   6.00 &       1.59 \\
LongerRMHA      &     0.71 &      4.00 &   6.00 &       1.14 \\
None            &     3.05 &      5.08 &   6.71 &       5.62 \\
RMHA            &     1.37 &      2.64 &   6.29 &       1.98 \\
RMHAROPEONE     &     2.82 &      6.54 &   4.29 &       5.46 \\
ROPEMHA         &     4.03 &      6.55 &   5.14 &       6.52 \\
Rotatory        &     3.92 &      6.10 &   9.00 &       4.92 \\
RotatoryCon     &     3.16 &      5.12 &   6.71 &       4.47 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12408\1530286203.py:6: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

In [30]:
print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

\begin{tabular}{lrrrr}
\toprule
{} &  dev\_hit &  dev\_ndcg &  runs &  CI-length \\
encoding        &          &           &       &            \\
\midrule
Abs             &     5.43 &      8.25 &  9.38 &       6.71 \\
AbsCon          &     3.52 &      5.56 &  7.12 &       5.35 \\
Learnt          &     4.79 &      7.64 &  7.88 &       7.05 \\
LearntCon       &     3.17 &      6.36 &  6.62 &       4.42 \\
LongROPEMHA     &     3.33 &      8.15 &  5.25 &       5.99 \\
LongRotatory    &     1.05 &      1.04 &  4.67 &       2.08 \\
LongRotatoryCon &     0.99 &      1.24 &  6.00 &       1.59 \\
LongerRMHA      &     0.71 &      4.00 &  6.00 &       1.14 \\
None            &     2.35 &      5.26 &  8.00 &       3.29 \\
RMHA            &     0.51 &      1.08 &  6.00 &       0.88 \\
RMHAROPEONE     &     2.82 &      6.54 &  4.29 &       5.46 \\
ROPEMHA         &     2.38 &      5.45 &  5.00 &       4.04 \\
Rotatory        &     2.46 &      5.01 &  8.38 &       3.48 \\
RotatoryCon     &     2.48 &      5.18 &  6.75 &       3.49 \\
\bottomrule
\end{tabular}

C:\Users\a00624448\AppData\Local\Temp\ipykernel_12408\1102116273.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(mean_values[["dev_hit","dev_ndcg","runs","CI-length"]].to_latex())

In [166]:
mean_values

              nmax  mean_hit  dev_hit  mean_ndcg  dev_ndcg   runs  CI-length
encoding
Abs           0.05     65.44     7.20      46.51      9.42  10.57       8.42
AbsCon        0.05     66.72     4.67      49.80      6.58   8.00       6.36
Learnt        0.05     68.59     7.43      48.76      9.98   9.07      10.17
LearntCon     0.05     65.32     4.09      47.34      6.53   6.93       5.66
LongROPEMHA   0.00     69.04     3.33      52.24      8.15   5.25       5.99
LongRotatory  0.05     55.60     1.56      36.75      1.63   2.00       4.32
None          0.05     63.28     3.06      45.64      5.08   6.64       5.63
RMHA          0.05     64.80     1.37      42.48      2.64   6.29       1.98
RMHAROPEONE   0.00     68.29     2.64      48.59      5.53   3.75       5.83
ROPEMHA       0.05     63.14     4.03      45.33      6.55   5.14       6.52
Rotatory      0.05     64.44     3.92      47.21      6.10   9.00       4.92
RotatoryCon   0.05     66.52     3.16      49.65      5.12   6.71       4.47

In [157]:
df[df['encoding']=='RMHAROPEONE']

,activation,encoding,nmax,ntype,mean_hit,dev_hit,mean_ndcg,dev_ndcg,runs,dataset,confidence_interval,confidence_interval_length
78,leaky,RMHAROPEONE,0.0001,2.0,73.03,6.52,62.96,8.59,3,fashion,"(65.65, 80.41)",14.76
79,silu,RMHAROPEONE,0.0001,2.0,71.70,1.82,51.07,11.17,3,fashion,"(69.64, 73.76)",4.12
66,leaky,RMHAROPEONE,0.0001,2.0,55.33,1.22,37.89,1.24,3,beauty,"(53.95, 56.71)",2.76
67,silu,RMHAROPEONE,0.0001,2.0,57.25,1.16,38.76,1.01,3,beauty,"(55.94, 58.56)",2.62
49,leaky,RMHAROPEONE,NaN,2.0,78.82,0.62,53.45,0.42,6,games,"(78.32, 79.32)",1.00
50,silu,RMHAROPEONE,NaN,2.0,78.27,1.19,52.85,0.88,6,games,"(77.32, 79.22)",1.90
70,leaky,RMHAROPEONE,0.0001,2.0,69.77,7.86,54.24,17.65,3,men,"(60.88, 78.66)",17.78
71,silu,RMHAROPEONE,0.0001,2.0,62.14,0.74,37.49,3.31,3,men,"(61.3, 62.98)",1.68

In [85]:
import math
import numpy as np

def process_dataframe(df):
    df1 = df[df['confidence_interval_length'] > 10]
    df1['confidence_interval_length'] = df1['confidence_interval_length'].apply(lambda x: math.ceil(x))
    df1['need'] = (np.floor(np.log(df1['confidence_interval_length'] - 10) / np.log(1.5)) + 1).astype(int)
    df1 = df1.drop(columns=["mean_hit", "dev_hit", "mean_ndcg", "dev_ndcg", "runs", "confidence_interval", "confidence_interval_length"])
    return df1

# dffashion = process_dataframe(dffashion)
# dfbeauty = process_dataframe(dfbeauty)
dfgames = process_dataframe(dfgames)

C:\Users\a00624448\AppData\Local\Temp\ipykernel_14080\3936825039.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['confidence_interval_length'] = df1['confidence_interval_length'].apply(lambda x: math.ceil(x))
C:\Users\a00624448\AppData\Local\Temp\ipykernel_14080\3936825039.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['need'] = (np.floor(np.log(df1['confidence_interval_length'] - 10) / np.log(1.5)) + 1).astype(int)

In [26]:
dfgames

  activation   encoding    nmax  ntype dataset  need
1       silu  LearntCon  0.0001    2.0   games     8
3       silu     AbsCon  0.0001    2.0   games     8
4       silu     Learnt  0.0001    2.0   games     8
5       silu        Abs  0.0001    2.0   games     9

In [112]:
df1 = dfbeauty
df1["need"].sum()

25

In [113]:
df1 = df1.rename(columns={'nmax': 'max_norm','ntype': 'norm_type',
                          'activation': 'hidden_act'})
print(df1.to_string(index=False))

hidden_act encoding  max_norm  norm_type dataset  need
      silu      con    0.1000        2.0  beauty     1
     leaky   learnt    0.1000        2.0  beauty     2
      silu   learnt    0.1000        2.0  beauty     7
     leaky    nocon    0.0001        2.0  beauty     1
      silu    nocon    0.0001        2.0  beauty     4
     leaky    nocon    0.1000        2.0  beauty     3
      silu    nocon    0.1000        2.0  beauty     7

carca_nmax_0.0001_ntype_0.0001_hact_leakyrelu
None
carca_nmax_0.0001_ntype_0.0001_hact_silu
carca_nmax_0.0001_ntype_0.0001_hact_silu
carca_nmax_0.0001_ntype_0.0001_hact_silu
carca_nmax_0.0001_ntype_0.0001_hact_silu
carca_nmax_0.0001_ntype_0.0001_hact_silu
carca_nmax_0.0001_ntype_0.0001_hact_silu
None
carca_nmax_0.0001_ntype_0.01_hact_leakyrelu
carca_nmax_0.0001_ntype_0.01_hact_leakyrelu
carca_nmax_0.0001_ntype_0.01_hact_leakyrelu
carca_nmax_0.0001_ntype_0.01_hact_leakyrelu
carca_nmax_0.0001_ntype_0.01_hact_leakyrelu
None
carca_nmax_0.0001_ntype_0.01_hact_silu
carca_nmax_0.0001_ntype_0.01_hact_silu
carca_nmax_0.0001_ntype_0.01_hact_silu
carca_nmax_0.0001_ntype_0.01_hact_silu
None
carca_nmax_0.0001_ntype_0.1_hact_leakyrelu
carca_nmax_0.0001_ntype_0.1_hact_leakyrelu
carca_nmax_0.0001_ntype_0.1_hact_leakyrelu
carca_nmax_0.0001_ntype_0.1_hact_leakyrelu
carca_nmax_0.0001_ntype_0.1_hact_leakyrelu
None
carca_nmax_0.0001_ntype_0.1_hact_silu
carca_nmax_0.0001_ntype_0.1_hact_silu
None
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
carca_nmax_0.1_ntype_0.0001_hact_leakyrelu
None
carca_nmax_0.1_ntype_0.0001_hact_silu
carca_nmax_0.1_ntype_0.0001_hact_silu
carca_nmax_0.1_ntype_0.0001_hact_silu
carca_nmax_0.1_ntype_0.0001_hact_silu
carca_nmax_0.1_ntype_0.0001_hact_silu
None
carca_nmax_0.1_ntype_0.01_hact_leakyrelu
carca_nmax_0.1_ntype_0.01_hact_leakyrelu
carca_nmax_0.1_ntype_0.01_hact_leakyrelu
carca_nmax_0.1_ntype_0.01_hact_leakyrelu
carca_nmax_0.1_ntype_0.01_hact_leakyrelu
None
carca_nmax_0.1_ntype_0.01_hact_silu
carca_nmax_0.1_ntype_0.01_hact_silu
carca_nmax_0.1_ntype_0.01_hact_silu
carca_nmax_0.1_ntype_0.01_hact_silu
carca_nmax_0.1_ntype_0.01_hact_silu
carca_nmax_0.1_ntype_0.01_hact_silu
None
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
carca_nmax_0.1_ntype_0.1_hact_leakyrelu
None
carca_nmax_0.1_ntype_0.1_hact_silu
carca_nmax_0.1_ntype_0.1_hact_silu
carca_nmax_0.1_ntype_0.1_hact_silu
carca_nmax_0.1_ntype_0.1_hact_silu
carca_nmax_0.1_ntype_0.1_hact_silu
None
carca_nmax_0.1_ntype_1.0_hact_leakyrelu
carca_nmax_0.1_ntype_1.0_hact_leakyrelu
carca_nmax_0.1_ntype_1.0_hact_leakyrelu
carca_nmax_0.1_ntype_1.0_hact_leakyrelu
carca_nmax_0.1_ntype_1.0_hact_leakyrelu
None
carca_nmax_0.1_ntype_1.0_hact_silu
carca_nmax_0.1_ntype_1.0_hact_silu
carca_nmax_0.1_ntype_1.0_hact_silu
carca_nmax_0.1_ntype_1.0_hact_silu
carca_nmax_0.1_ntype_1.0_hact_silu
None
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
carca_nmax_0.5_ntype_0.0001_hact_leakyrelu
None
carca_nmax_0.5_ntype_0.0001_hact_silu
carca_nmax_0.5_ntype_0.0001_hact_silu
carca_nmax_0.5_ntype_0.0001_hact_silu
carca_nmax_0.5_ntype_0.0001_hact_silu
carca_nmax_0.5_ntype_0.0001_hact_silu
None
carca_nmax_0.5_ntype_0.01_hact_leakyrelu
carca_nmax_0.5_ntype_0.01_hact_leakyrelu
carca_nmax_0.5_ntype_0.01_hact_leakyrelu
None
carca_nmax_0.5_ntype_0.01_hact_silu
carca_nmax_0.5_ntype_0.01_hact_silu
carca_nmax_0.5_ntype_0.01_hact_silu
carca_nmax_0.5_ntype_0.01_hact_silu
carca_nmax_0.5_ntype_0.01_hact_silu
carca_nmax_0.5_ntype_0.01_hact_silu
None
carca_nmax_0.5_ntype_0.1_hact_leakyrelu
carca_nmax_0.5_ntype_0.1_hact_leakyrelu
carca_nmax_0.5_ntype_0.1_hact_leakyrelu
None
carca_nmax_0.5_ntype_0.1_hact_silu
carca_nmax_0.5_ntype_0.1_hact_silu
carca_nmax_0.5_ntype_0.1_hact_silu
carca_nmax_0.5_ntype_0.1_hact_silu
carca_nmax_0.5_ntype_0.1_hact_silu
None
carca_nmax_0.5_ntype_1.0_hact_leakyrelu
carca_nmax_0.5_ntype_1.0_hact_leakyrelu
carca_nmax_0.5_ntype_1.0_hact_leakyrelu
carca_nmax_0.5_ntype_1.0_hact_leakyrelu
None
carca_nmax_0.5_ntype_1.0_hact_silu
carca_nmax_0.5_ntype_1.0_hact_silu
carca_nmax_0.5_ntype_1.0_hact_silu
carca_nmax_0.5_ntype_1.0_hact_silu
carca_nmax_0.5_ntype_1.0_hact_silu
None
carca_nmax_1.0_ntype_0.0001_hact_leakyrelu
carca_nmax_1.0_ntype_0.0001_hact_leakyrelu
carca_nmax_1.0_ntype_0.0001_hact_leakyrelu
carca_nmax_1.0_ntype_0.0001_hact_leakyrelu
carca_nmax_1.0_ntype_0.0001_hact_leakyrelu
None
carca_nmax_1.0_ntype_0.01_hact_leakyrelu
carca_nmax_1.0_ntype_0.01_hact_leakyrelu
carca_nmax_1.0_ntype_0.01_hact_leakyrelu
carca_nmax_1.0_ntype_0.01_hact_leakyrelu
None
carca_nmax_1.0_ntype_0.01_hact_silu
carca_nmax_1.0_ntype_0.01_hact_silu
carca_nmax_1.0_ntype_0.01_hact_silu
carca_nmax_1.0_ntype_0.01_hact_silu
carca_nmax_1.0_ntype_0.01_hact_silu
carca_nmax_1.0_ntype_0.01_hact_silu
None
carca_nmax_1.0_ntype_0.1_hact_silu
carca_nmax_1.0_ntype_0.1_hact_silu
carca_nmax_1.0_ntype_0.1_hact_silu
carca_nmax_1.0_ntype_0.1_hact_silu
None
carca_nmax_1.0_ntype_1.0_hact_silu
carca_nmax_1.0_ntype_1.0_hact_silu
carca_nmax_1.0_ntype_1.0_hact_silu
None
carca_nmax_nan_ntype_0.0001_hact_leakyrelu
carca_nmax_nan_ntype_0.0001_hact_leakyrelu
carca_nmax_nan_ntype_0.0001_hact_leakyrelu
carca_nmax_nan_ntype_0.0001_hact_leakyrelu
carca_nmax_nan_ntype_0.0001_hact_leakyrelu
None
carca_nmax_nan_ntype_0.0001_hact_silu
carca_nmax_nan_ntype_0.0001_hact_silu
carca_nmax_nan_ntype_0.0001_hact_silu
carca_nmax_nan_ntype_0.0001_hact_silu
None
carca_nmax_nan_ntype_0.01_hact_leakyrelu
carca_nmax_nan_ntype_0.01_hact_leakyrelu
carca_nmax_nan_ntype_0.01_hact_leakyrelu
carca_nmax_nan_ntype_0.01_hact_leakyrelu
carca_nmax_nan_ntype_0.01_hact_leakyrelu
None
carca_nmax_nan_ntype_0.01_hact_silu
carca_nmax_nan_ntype_0.01_hact_silu
carca_nmax_nan_ntype_0.01_hact_silu
carca_nmax_nan_ntype_0.01_hact_silu
carca_nmax_nan_ntype_0.01_hact_silu
carca_nmax_nan_ntype_0.01_hact_silu
None
carca_nmax_nan_ntype_0.1_hact_leakyrelu
carca_nmax_nan_ntype_0.1_hact_leakyrelu
carca_nmax_nan_ntype_0.1_hact_leakyrelu
carca_nmax_nan_ntype_0.1_hact_leakyrelu
None
carca_nmax_nan_ntype_0.1_hact_silu
carca_nmax_nan_ntype_0.1_hact_silu
carca_nmax_nan_ntype_0.1_hact_silu
carca_nmax_nan_ntype_0.1_hact_silu
None
carca_nmax_nan_ntype_1.0_hact_leakyrelu
carca_nmax_nan_ntype_1.0_hact_leakyrelu
carca_nmax_nan_ntype_1.0_hact_leakyrelu
carca_nmax_nan_ntype_1.0_hact_leakyrelu
None
carca_nmax_nan_ntype_1.0_hact_silu
carca_nmax_nan_ntype_1.0_hact_silu
carca_nmax_nan_ntype_1.0_hact_silu
carca_nmax_nan_ntype_1.0_hact_silu
carca_nmax_nan_ntype_1.0_hact_silu
carca_nmax_nan_ntype_1.0_hact_silu
None
carca_nmax_0.0001_ntype_2.0_hact_leakyrelu
None
carca_nmax_0.1_ntype_2.0_hact_leakyrelu
None
carca_nmax_0.1_ntype_2.0_hact_silu
carca_nmax_0.1_ntype_2.0_hact_silu
None
carca_nmax_0.0001_ntype_2.0_hact_silu
None
carca_nmax_0.1_ntype_2.0_hact_leakyrelu
carca_nmax_0.1_ntype_2.0_hact_leakyrelu
carca_nmax_0.1_ntype_2.0_hact_leakyrelu
carca_nmax_0.1_ntype_2.0_hact_leakyrelu
None
carca_nmax_0.1_ntype_2.0_hact_silu
carca_nmax_0.1_ntype_2.0_hact_silu
carca_nmax_0.1_ntype_2.0_hact_silu
carca_nmax_0.1_ntype_2.0_hact_silu
carca_nmax_0.1_ntype_2.0_hact_silu
None
carca_nmax_0.1_ntype_2.0_hact_silu
None
carca_nmax_0.1_ntype_2.0_hact_silu
None

In [44]:
(df1['need'].sum() * 4)/22

31.454545454545453

In [37]:
# column_order = ['dataset','encoding', 'activation', 'nmax', 'mean_hit', 'dev_hit', 'mean_ndcg', 'dev_ndcg', 'runs']  # Replace with your actual column names

# # Concatenate the DataFrames and choose the column order
# result_df = pd.concat([df1, df2, df3], ignore_index=True)[column_order]
# # result_df.to_string(index=False)
# def dataframe_to_latex(df):
#     """
#     Convert a DataFrame to a LaTeX table.

#     Parameters:
#     - df: DataFrame with columns "dataset", "encoding", "activation", "nmax", "mean_hit", "dev_hit", "mean_ndcg", "dev_ndcg".

#     Returns:
#     - LaTeX table as a string.
#     """
#     # Check if the DataFrame has the required columns
#     required_columns = ["dataset", "encoding", "activation", "nmax", "mean_hit", "dev_hit", "mean_ndcg", "dev_ndcg"]
#     if not set(required_columns).issubset(df.columns):
#         raise ValueError("DataFrame is missing required columns.")

#     # Convert DataFrame to LaTeX table
#     latex_table = df.to_latex(index=False, escape=False)

#     return latex_table

# latex_table = dataframe_to_latex(result_df)

NameError: name 'df1' is not defined

In [26]:
from scipy.stats import ttest_1samp

# Assuming 'data' is a NumPy array or a list containing your performance measurements
reference_value = 0.550  # The value you want to compare against
data = np.array([42.5, 59.53, 43.11, 35.72, 63.72, 34.86])

# Perform one-sample t-test
t_stat, p_value = ttest_1samp(data, reference_value)

# Check if the p-value is less than the significance level (e.g., 0.05)
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. The mean performance is significantly different.")
else:
    print("Fail to reject the null hypothesis. The mean performance is not significantly different.")
p_value

Reject the null hypothesis. The mean performance is significantly different.

In [5]:
# Define the threshold value
threshold_value = 70

# Highlight entries equal or higher than the threshold
def highlight_greater_or_equal(val):
    return 'background-color: grey' if val >= threshold_value else ''

# Specify the columns you want to apply the styling to
columns_to_style = ['mean_hit', 'mean_ndcg']

# Apply the function to the specified columns
styled_df = dfmen[condition].style.applymap(highlight_greater_or_equal, subset=pd.IndexSlice[:, columns_to_style])


# Display the styled DataFrame
styled_df

### Check means of the deviations

In [100]:
for (df1, name) in [(dfsubfashion, "subfashion"), (dfsubmen, "submen")]:
    df1 = df1.dropna(axis=0)
    print(name)
    print(df1['dev_hit'].mean())
    print(df1['dev_ndcg'].mean())

subfashion
13.988333333333332
16.606666666666666
submen
6.295833333333332
7.951666666666667

In [20]:
for (df1, name) in [(dfmen, "men"), (dfgames, "games"), (dfbeauty, "beauty"), (dffashion, "fashion")]:
    df1 = df1.dropna(axis=0)
    print(name)
    print(df1['dev_hit'].mean())
    print(df1['dev_ndcg'].mean())
#     for case in ['carcanmax', 'connmax', 'noconnmax', 'RMHA']:
#         print(name, case)
# #         print(df1[df1["encoding"]==case].corr())
#         print("\n")

men
4.257777777777778
7.747777777777778
games
3.2090909090909094
2.87030303030303
beauty
3.9856
3.4664000000000006
fashion
6.164444444444444
10.34611111111111